global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus_job"
    static_configs:
      - targets: ["localhost:9090"]

  # Create a job for Docker Swarm containers.
  - job_name: "_job"
    tls_config:
      ca_file: /run/secrets/ca-cert
      cert_file: /run/secrets/client-cert
      key_file: /run/secrets/client-key

    dockerswarm_sd_configs:
      - host: "tcp://178.212.35.106:2375" # unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
        # Filter out internal overlay IPs (keep only public/external)
      - source_labels: [__address__]
        regex: 10\..*
        action: drop
